export default {
  "login": "mohitchandak",
   "id": 65466004,
   "node_id": "MDQ6VXNlcjY1NDY2MDA0",
   "avatar_url": "https://avatars.githubusercontent.com/u/65466004?v=4",
   "gravatar_id": "",
   "url": "https://api.github.com/users/mohitchandak",
   "html_url": "https://github.com/mohitchandak",
   "followers_url": "https://api.github.com/users/mohitchandak/followers",
   "following_url": "https://api.github.com/users/mohitchandak/following{/other_user}",
   "gists_url": "https://api.github.com/users/mohitchandak/gists{/gist_id}",
   "starred_url": "https://api.github.com/users/mohitchandak/starred{/owner}{/repo}",
   "subscriptions_url": "https://api.github.com/users/mohitchandak/subscriptions",
   "organizations_url": "https://api.github.com/users/mohitchandak/orgs",
   "repos_url": "https://api.github.com/users/mohitchandak/repos",
   "events_url": "https://api.github.com/users/mohitchandak/events{/privacy}",
   "received_events_url": "https://api.github.com/users/mohitchandak/received_events",
   "type": "User",
   "site_admin": false,
   "name": "Mohit Chandak",
   "company": "Shri Ramdeobaba College of Engineering and Management",
   "blog": "",
   "location": "Nagpur",
   "email": null,
   "hireable": null,
   "bio": null,
   "twitter_username": null,
   "public_repos": 8,
   "public_gists": 0,
   "followers": 7,
   "following": 9,
   "created_at": "2020-05-16T19:37:57Z",
   "updated_at": "2022-01-24T16:06:00Z"
 
};
